export type ColorResponse = {
    id: number,
    product_id: number,
    color_name: string,
    color_code: string,
    status: number,
    statusLabel: string,
    price: number,
    discountedPrice: number,
    discount: number,
    delivery_delay: number,
    stock: number,
    created_at: string,
    updated_at: string,
}
